### ISSUE TITLE
Redirect Kivabe kore?

### ISSUE THREAD

**Issue by Saidul13** [karim-007/laravel-bkash#2]
payment complete korar pore Redirect Kivabe kore? ami success function theke koresilam hoy na

**Comment by Saidul13** [comment]
payment complete korar pore Redirect Kivabe kore? ami success function theke koresilam hoy na, Please help me

**Comment by Saidul13** [comment]
ata kon file ase? ami to nirdesona unujaye BkashPaymentControllere jegulo function ase sekhane use korsilam

**Comment by Minhazul-Islam18** [comment]
config/bkash.php
"callbackURL"     => env("BKASH_CALLBACK_URL", "http://127.0.0.1:8000"),

or

.env
BKASH_CALLBACK_URL = http://127.0.0.1:8000

**Comment by Saidul13** [comment]
ata to kono kaj kore na

**Comment by karim-007** [comment]
do you know laravel? please read laravel documentation properly before doing any laravel project from here https://laravel.com/ . thank you
