### ISSUE TITLE
Bkash Payment Issu 

### ISSUE THREAD

**Issue by dev-raufhossain** [karim-007/laravel-bkash#3]
![Screenshot_299](https://github.com/karim-007/laravel-bkash/assets/107985855/9e212870-91f0-474c-b064-653c1c581ba6)

URL: http://127.0.0.1:8000/bkash/callback?paymentID=TR0011GfmE7Oa1717299259288&status=failure&apiVersion=1.2.0-beta

**Comment by karim-007** [comment]
Your transaction is fail thats why it showing. if it will be success then it showing success message.
